// app/layout.tsx
import { ReactNode } from "react";
import { CopilotKit } from "@copilotkit/react-core"; 
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@copilotkit/react-ui/styles.css";

import { CopilotFeaturesProvider } from "./providers/CopilotFeaturesProvider";
import { InteleosContextProvider } from "./contexts/InteleosContext";
import { Toaster } from "@/components/ui/toaster"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CopilotKit runtimeUrl="/api/copilotkit"> 
          <InteleosContextProvider>
          <CopilotFeaturesProvider>
            {children}
            <Toaster />
          </CopilotFeaturesProvider>
          </InteleosContextProvider>
        </CopilotKit>
      </body>
    </html>
  );
}
